sonar.projectKey=yasir239_devsecops-demo
sonar.organization=yasir239
sonar.projectName=DevSecOps Demo
sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/htmlcov/**
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
